### ISSUE TITLE
unable to connect my meta mask wallet to site

### ISSUE THREAD

**Issue by nuni007** [wise-foundation/wise-website-bug-reports#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nuni007** [comment]
cant connect metamask wallet to site....no respond

**Comment by coffee-converter** [comment]
> cant connect metamask wallet to site....no respond

You'll have to provide more info in order for me to diagnose your issue.  Screenshots?  Reproduction steps?  Please fill in as many of the details as you can:

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Version [e.g. 22]
Smartphone (please complete the following information):

Device: [e.g. iPhone6]
OS: [e.g. iOS8.1]
Browser [e.g. stock browser, safari]
Version [e.g. 22]
Additional context
Add any other context about the problem here.

**Comment by nuni007** [comment]
I use desktop ChromeVersion 89.0.4389.128 official buildSent from my T-Mobile 5G Device
-------- Original message --------From: Coffee Converter ***@***.***> Date: 4/14/21  10:44 AM  (GMT-08:00) To: wise-foundation/wise-website-requests ***@***.***> Cc: nuni007 ***@***.***>, Author ***@***.***> Subject: Re: [wise-foundation/wise-website-requests] unable to connect my meta
  mask wallet to site (#40) 

cant connect metamask wallet to site....no respond

You'll have to provide more info in order for me to diagnose your issue.  Screenshots?  Reproduction steps?  Please fill in as many of the details as you can:
Describe the bug
A clear and concise description of what the bug is.
To Reproduce
Steps to reproduce the behavior:
Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.
Screenshots
If applicable, add screenshots to help explain your problem.
Desktop (please complete the following information):
OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Version [e.g. 22]
Smartphone (please complete the following information):
Device: [e.g. iPhone6]
OS: [e.g. iOS8.1]
Browser [e.g. stock browser, safari]
Version [e.g. 22]
Additional context
Add any other context about the problem here.

**Comment by coffee-converter** [comment]
It would be great if you could provide the rest of the info...hard to help otherwise.  I can't tell what you're doing wrong on your Chrome metamask since you've given no steps/screenshots.  Are you on the correct network?  Have you tried resetting your Metamask in advanced settings?

**Comment by nuni007** [comment]
Thank you it's done....had to go to settings first.....Sent from my T-Mobile 5G Device
-------- Original message --------From: Coffee Converter ***@***.***> Date: 4/14/21  11:03 AM  (GMT-08:00) To: wise-foundation/wise-website-requests ***@***.***> Cc: nuni007 ***@***.***>, Author ***@***.***> Subject: Re: [wise-foundation/wise-website-requests] unable to connect my meta
  mask wallet to site (#40) 
It would be great if you could provide the rest of the info...hard to help otherwise.  I can't tell what you're doing wrong on your Chrome metamask since you've given no steps/screenshots.  Are you on the correct network?  Have you tried resetting your Metamask in advanced settings?

**Comment by nuni007** [comment]
Awesome, thanks!
